<?php

namespace Database\Seeders;

use App\Http\Services\RecipeIngredientSync;
use App\Models\Category;
use App\Models\Recipe;
use App\Models\User;
use App\Support\DishArtwork;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

/**
 * Demo content for the Cuisine Map Explorer, pantry matching and the
 * nutrition panel — enough countries and ingredient overlap that the
 * "what can I cook?" search returns something interesting straight away.
 */
class RecipeSeeder extends Seeder
{
    public function __construct(private RecipeIngredientSync $sync)
    {
    }

    private const COOKS = [
        ['Maria Rossi', 'maria', 'maria@fridgemama.test'],
        ['Rahim Chowdhury', 'rahim', 'rahim@fridgemama.test'],
        ['Yuki Tanaka', 'yuki', 'yuki@fridgemama.test'],
        ['Ana Flores', 'ana', 'ana@fridgemama.test'],
        ['Amara Okafor', 'amara', 'amara@fridgemama.test'],
        ['Tomas Novak', 'tomas', 'tomas@fridgemama.test'],
    ];

    private const RECIPES = [
        [
            'title' => 'Spaghetti Aglio e Olio',
            'cook' => 'maria',
            'country' => 'IT',
            'difficulty' => 'beginner',
            'prep' => 5, 'cook_min' => 15, 'servings' => 2,
            'categories' => ['Dinner', 'Quick Meals', 'Italian'],
            'diets' => ['vegetarian', 'dairy-free'],
            'description' => 'The five-ingredient Roman classic — pasta, garlic, chilli and good olive oil. On the table faster than a delivery order.',
            'ingredients' => [
                '200 g spaghetti',
                '4 cloves garlic, thinly sliced',
                '4 tbsp olive oil',
                '1 green chilli, chopped',
                '2 tbsp parsley, chopped',
                '1 tsp salt',
            ],
            'instructions' => [
                'Bring a large pot of salted water to the boil and cook the spaghetti for 9 minutes until al dente.',
                'Meanwhile warm the olive oil in a wide pan over low heat and add the sliced garlic and chilli.',
                'Fry gently for 3 minutes until the garlic is pale gold — do not let it brown.',
                'Drain the pasta, reserving a cup of the cooking water, and add it to the pan.',
                'Toss for 1 minute with a splash of pasta water until glossy, then finish with parsley.',
            ],
        ],
        [
            'title' => 'Classic Margherita Pizza',
            'cook' => 'maria',
            'country' => 'IT',
            'difficulty' => 'intermediate',
            'prep' => 90, 'cook_min' => 12, 'servings' => 2,
            'categories' => ['Dinner', 'Italian'],
            'diets' => ['vegetarian'],
            'description' => 'Slow-risen dough, crushed tomatoes, mozzarella and basil. Nothing else — that is the whole point.',
            'ingredients' => [
                '300 g flour',
                '7 g yeast',
                '200 ml water',
                '1 tsp salt',
                '2 tbsp olive oil',
                '200 g chopped tomatoes',
                '150 g mozzarella',
                '10 g basil',
            ],
            'instructions' => [
                'Mix the flour, yeast, salt and water into a shaggy dough, then knead for 8 minutes until smooth.',
                'Cover and leave to rise for 60 minutes until doubled in size.',
                'Heat the oven to its highest setting with a baking tray inside for 20 minutes.',
                'Stretch the dough, spread with crushed tomatoes and tear the mozzarella over the top.',
                'Bake for 10 minutes until the crust is blistered, then finish with basil and olive oil.',
            ],
        ],
        [
            'title' => 'Bengali Chicken Curry',
            'cook' => 'rahim',
            'country' => 'BD',
            'difficulty' => 'intermediate',
            'prep' => 20, 'cook_min' => 40, 'servings' => 4,
            'categories' => ['Dinner', 'Bengali'],
            'diets' => ['halal', 'gluten-free', 'dairy-free'],
            'description' => 'A weeknight kosha-style curry: onions cooked down properly, whole spices, and chicken that falls off the bone.',
            'ingredients' => [
                '800 g chicken thigh',
                '3 onions, thinly sliced',
                '5 cloves garlic',
                '1 tbsp ginger',
                '2 tomatoes, chopped',
                '1 tsp turmeric',
                '2 tsp chilli powder',
                '1 tsp cumin',
                '1 tsp garam masala',
                '4 tbsp vegetable oil',
                '2 bay leaves',
                '1 tsp salt',
            ],
            'instructions' => [
                'Heat the oil in a heavy pan and fry the bay leaves for 30 seconds until fragrant.',
                'Add the sliced onions and cook over medium heat for 15 minutes until deep golden.',
                'Stir in the garlic and ginger and fry for 2 minutes.',
                'Add the turmeric, chilli powder and cumin with a splash of water and cook the spices for 3 minutes.',
                'Add the chicken and tomatoes, season with salt, cover and simmer for 25 minutes.',
                'Uncover, raise the heat and reduce the sauce for 5 minutes, then finish with garam masala.',
            ],
        ],
        [
            'title' => 'Red Lentil Dal',
            'cook' => 'rahim',
            'country' => 'BD',
            'difficulty' => 'beginner',
            'prep' => 5, 'cook_min' => 25, 'servings' => 4,
            'categories' => ['Lunch', 'Vegan', 'Quick Meals'],
            'diets' => ['vegetarian', 'vegan', 'gluten-free', 'dairy-free', 'halal'],
            'description' => 'Store-cupboard comfort food. Lentils, turmeric, and a sizzling spice tempering poured over at the end.',
            'ingredients' => [
                '250 g lentils',
                '1 onion, chopped',
                '3 cloves garlic',
                '1 tsp turmeric',
                '1 tsp cumin',
                '2 green chillies',
                '3 tbsp vegetable oil',
                '1 tsp salt',
                '750 ml water',
            ],
            'instructions' => [
                'Rinse the lentils until the water runs clear.',
                'Simmer the lentils with turmeric and water for 20 minutes until completely soft.',
                'Heat the oil in a small pan, add the cumin and let it crackle for 30 seconds.',
                'Add the onion, garlic and chillies and fry for 4 minutes until golden.',
                'Pour the tempering into the lentils, season with salt and stir through.',
            ],
        ],
        [
            'title' => 'Chicken Katsu Curry',
            'cook' => 'yuki',
            'country' => 'JP',
            'difficulty' => 'intermediate',
            'prep' => 20, 'cook_min' => 30, 'servings' => 2,
            'categories' => ['Dinner'],
            'diets' => ['dairy-free'],
            'description' => 'Crisp panko-crumbed chicken over rice, with a mellow, faintly sweet Japanese curry sauce.',
            'ingredients' => [
                '2 chicken breasts',
                '100 g breadcrumbs',
                '1 egg',
                '50 g flour',
                '200 g rice',
                '1 onion, sliced',
                '1 carrot, diced',
                '2 tbsp curry powder',
                '400 ml stock',
                '2 tbsp soy sauce',
                '3 tbsp vegetable oil',
            ],
            'instructions' => [
                'Rinse the rice and cook it for 12 minutes, then leave it covered to steam.',
                'Fry the onion and carrot in oil for 6 minutes until softening.',
                'Stir in the curry powder, cook for 1 minute, then add the stock and soy sauce.',
                'Simmer the sauce for 15 minutes until it coats a spoon.',
                'Coat the chicken in flour, then egg, then breadcrumbs, and fry for 4 minutes per side.',
                'Rest the chicken for 2 minutes, slice, and serve over rice with the sauce.',
            ],
        ],
        [
            'title' => 'Miso Salmon with Greens',
            'cook' => 'yuki',
            'country' => 'JP',
            'difficulty' => 'beginner',
            'prep' => 10, 'cook_min' => 15, 'servings' => 2,
            'categories' => ['Dinner', 'Seafood', 'Quick Meals'],
            'diets' => ['pescatarian', 'dairy-free', 'high-protein'],
            'description' => 'A glazed salmon fillet under the grill while the greens steam. Fifteen minutes, one tray.',
            'ingredients' => [
                '2 salmon fillets',
                '2 tbsp soy sauce',
                '1 tbsp honey',
                '1 tbsp ginger',
                '200 g broccoli',
                '2 spring onions',
                '1 tbsp vegetable oil',
            ],
            'instructions' => [
                'Mix the soy sauce, honey and grated ginger into a glaze.',
                'Brush the salmon and leave it to sit for 5 minutes.',
                'Grill the salmon for 10 minutes until it flakes easily.',
                'Steam the broccoli for 4 minutes until bright green.',
                'Scatter with sliced spring onions and serve.',
            ],
        ],
        [
            'title' => 'Black Bean Tacos',
            'cook' => 'ana',
            'country' => 'MX',
            'difficulty' => 'beginner',
            'prep' => 10, 'cook_min' => 15, 'servings' => 3,
            'categories' => ['Lunch', 'Vegan', 'Street Food'],
            'diets' => ['vegetarian', 'vegan', 'dairy-free'],
            'description' => 'Smoky black beans, quick pickled onion and avocado, folded into warm tortillas.',
            'ingredients' => [
                '400 g black beans',
                '6 tortillas',
                '1 onion, sliced',
                '2 cloves garlic',
                '1 tsp cumin',
                '1 tsp paprika',
                '1 avocado',
                '1 lime',
                '2 tbsp coriander',
                '2 tbsp olive oil',
            ],
            'instructions' => [
                'Fry the onion and garlic in oil for 5 minutes until soft.',
                'Add the cumin and paprika and cook for 1 minute.',
                'Tip in the beans with a splash of water and simmer for 8 minutes, crushing some against the pan.',
                'Warm the tortillas for 30 seconds each in a dry pan.',
                'Fill with beans, sliced avocado, coriander and a squeeze of lime.',
            ],
        ],
        [
            'title' => 'Chicken Tinga Bowls',
            'cook' => 'ana',
            'country' => 'MX',
            'difficulty' => 'intermediate',
            'prep' => 15, 'cook_min' => 35, 'servings' => 4,
            'categories' => ['Dinner'],
            'diets' => ['gluten-free', 'dairy-free', 'high-protein'],
            'description' => 'Shredded chicken braised in smoky chipotle tomato sauce, piled over rice with avocado.',
            'ingredients' => [
                '600 g chicken breast',
                '400 g chopped tomatoes',
                '2 onions',
                '4 cloves garlic',
                '2 tsp paprika',
                '1 tsp cumin',
                '300 ml stock',
                '250 g rice',
                '1 avocado',
                '2 tbsp vegetable oil',
            ],
            'instructions' => [
                'Poach the chicken in the stock for 18 minutes, then shred it with two forks.',
                'Fry the onions and garlic in oil for 8 minutes until soft and sweet.',
                'Add the paprika and cumin, cook for 1 minute, then pour in the tomatoes.',
                'Simmer the sauce for 10 minutes until thickened.',
                'Return the shredded chicken to the pan and warm through for 5 minutes.',
                'Serve over rice with sliced avocado.',
            ],
        ],
        [
            'title' => 'Thai Green Curry',
            'cook' => 'yuki',
            'country' => 'TH',
            'difficulty' => 'intermediate',
            'prep' => 15, 'cook_min' => 25, 'servings' => 4,
            'categories' => ['Dinner'],
            'diets' => ['gluten-free', 'dairy-free'],
            'description' => 'Coconut milk, green chilli and basil, with whatever vegetables are in the drawer.',
            'ingredients' => [
                '400 ml coconut milk',
                '400 g chicken thigh',
                '2 green chillies',
                '3 cloves garlic',
                '1 tbsp ginger',
                '1 aubergine, diced',
                '100 g peas',
                '2 tbsp soy sauce',
                '10 g basil',
                '2 tbsp vegetable oil',
            ],
            'instructions' => [
                'Blitz the chillies, garlic and ginger into a rough paste.',
                'Fry the paste in oil for 3 minutes until fragrant.',
                'Add the chicken and brown for 5 minutes.',
                'Pour in the coconut milk and simmer for 12 minutes.',
                'Add the aubergine and peas and cook for 6 minutes until tender.',
                'Season with soy sauce and stir through the basil off the heat.',
            ],
        ],
        [
            'title' => 'Greek Salad with Warm Pita',
            'cook' => 'maria',
            'country' => 'GR',
            'difficulty' => 'beginner',
            'prep' => 15, 'cook_min' => 5, 'servings' => 2,
            'categories' => ['Lunch', 'Quick Meals'],
            'diets' => ['vegetarian'],
            'description' => 'Cucumber, tomato and oregano, dressed in nothing but good olive oil and lemon.',
            'ingredients' => [
                '3 tomatoes',
                '1 cucumber',
                '1 onion',
                '100 g cheddar cheese',
                '3 tbsp olive oil',
                '1 lemon',
                '1 tsp oregano',
                '2 bread rolls',
            ],
            'instructions' => [
                'Chop the tomatoes, cucumber and onion into large, confident chunks.',
                'Whisk the olive oil with the juice of the lemon and the oregano.',
                'Toss everything together and let it sit for 10 minutes so the juices mingle.',
                'Warm the bread for 3 minutes and serve alongside.',
            ],
        ],
        [
            'title' => 'Shakshuka',
            'cook' => 'rahim',
            'country' => 'IL',
            'difficulty' => 'beginner',
            'prep' => 10, 'cook_min' => 20, 'servings' => 2,
            'categories' => ['Breakfast', 'Quick Meals'],
            'diets' => ['vegetarian', 'gluten-free'],
            'description' => 'Eggs poached in a spiced pepper and tomato sauce, straight from pan to table.',
            'ingredients' => [
                '4 eggs',
                '400 g chopped tomatoes',
                '2 bell peppers',
                '1 onion',
                '3 cloves garlic',
                '1 tsp cumin',
                '1 tsp paprika',
                '2 tbsp olive oil',
                '2 tbsp parsley',
            ],
            'instructions' => [
                'Fry the onion and peppers in olive oil for 8 minutes until soft.',
                'Add the garlic, cumin and paprika and cook for 1 minute.',
                'Pour in the tomatoes and simmer for 8 minutes until thick.',
                'Make four wells, crack in the eggs, cover and cook for 6 minutes until the whites set.',
                'Scatter with parsley and serve from the pan.',
            ],
        ],
        [
            'title' => 'Moroccan Chickpea Tagine',
            'cook' => 'ana',
            'country' => 'MA',
            'difficulty' => 'beginner',
            'prep' => 15, 'cook_min' => 35, 'servings' => 4,
            'categories' => ['Dinner', 'Vegan'],
            'diets' => ['vegetarian', 'vegan', 'gluten-free', 'dairy-free', 'halal'],
            'description' => 'Sweet potato, chickpeas and cinnamon, slow-cooked until everything collapses into the sauce.',
            'ingredients' => [
                '400 g chickpeas',
                '2 sweet potatoes',
                '1 onion',
                '3 cloves garlic',
                '400 g chopped tomatoes',
                '1 tsp cinnamon',
                '2 tsp cumin',
                '400 ml stock',
                '2 tbsp olive oil',
                '2 tbsp coriander',
            ],
            'instructions' => [
                'Fry the onion in olive oil for 6 minutes until translucent.',
                'Add the garlic, cumin and cinnamon and cook for 1 minute.',
                'Add the sweet potato, chickpeas, tomatoes and stock.',
                'Cover and simmer for 25 minutes until the sweet potato is tender.',
                'Uncover and reduce for 5 minutes, then finish with coriander.',
            ],
        ],
        [
            'title' => 'Full English Breakfast Hash',
            'cook' => 'maria',
            'country' => 'GB',
            'difficulty' => 'beginner',
            'prep' => 10, 'cook_min' => 25, 'servings' => 2,
            'categories' => ['Breakfast'],
            'diets' => ['high-protein'],
            'description' => 'Everything from the fry-up in one pan, with crisp potatoes underneath.',
            'ingredients' => [
                '400 g potatoes',
                '4 rashers bacon',
                '2 eggs',
                '200 g mushrooms',
                '2 tomatoes',
                '2 tbsp vegetable oil',
                '1 tsp black pepper',
            ],
            'instructions' => [
                'Parboil the diced potatoes for 8 minutes, then drain and dry them well.',
                'Fry the bacon for 4 minutes until crisp, then set it aside.',
                'Fry the potatoes in the bacon fat for 10 minutes without stirring too often.',
                'Add the mushrooms and tomatoes and cook for 5 minutes.',
                'Crack in the eggs, cover, and cook for 3 minutes until just set.',
            ],
        ],
        [
            'title' => 'Beef Bulgogi Rice Bowl',
            'cook' => 'yuki',
            'country' => 'KR',
            'difficulty' => 'intermediate',
            'prep' => 30, 'cook_min' => 12, 'servings' => 3,
            'categories' => ['Dinner'],
            'diets' => ['dairy-free', 'high-protein'],
            'description' => 'Sweet-salty marinated beef seared hard and fast, over rice with pickled cucumber.',
            'ingredients' => [
                '500 g beef mince',
                '4 tbsp soy sauce',
                '2 tbsp sugar',
                '1 tbsp ginger',
                '4 cloves garlic',
                '2 spring onions',
                '250 g rice',
                '1 cucumber',
                '2 tbsp vegetable oil',
            ],
            'instructions' => [
                'Mix the soy sauce, sugar, grated ginger and garlic into a marinade.',
                'Toss the beef through it and leave for 20 minutes.',
                'Cook the rice for 12 minutes and leave it covered.',
                'Sear the beef in a very hot pan for 5 minutes without crowding it.',
                'Serve over rice with sliced cucumber and spring onion.',
            ],
        ],
        [
            'title' => 'Vietnamese Chicken Pho',
            'cook' => 'yuki',
            'country' => 'VN',
            'difficulty' => 'advanced',
            'prep' => 20, 'cook_min' => 90, 'servings' => 4,
            'categories' => ['Dinner'],
            'diets' => ['dairy-free'],
            'description' => 'A long, patient broth with charred ginger and onion — the part you cannot rush.',
            'ingredients' => [
                '1 kg chicken thigh',
                '2 onions',
                '50 g ginger',
                '3 cardamom pods',
                '1 cinnamon stick',
                '2 tbsp soy sauce',
                '300 g noodles',
                '2 spring onions',
                '20 g coriander',
                '2 limes',
            ],
            'instructions' => [
                'Char the halved onions and ginger under a hot grill for 8 minutes until blackened at the edges.',
                'Add them to a pot with the chicken, cardamom, cinnamon and 3 litres of water.',
                'Simmer gently for 75 minutes, skimming the surface every so often.',
                'Lift out the chicken, shred the meat, and season the broth with soy sauce.',
                'Soak the noodles for 5 minutes in hot water, then divide between bowls.',
                'Ladle over the broth and top with chicken, herbs and a wedge of lime.',
            ],
        ],
        [
            'title' => 'Paneer-Style Tofu Tikka',
            'cook' => 'rahim',
            'country' => 'IN',
            'difficulty' => 'beginner',
            'prep' => 30, 'cook_min' => 20, 'servings' => 3,
            'categories' => ['Dinner', 'Vegan'],
            'diets' => ['vegetarian', 'vegan', 'gluten-free', 'dairy-free', 'high-protein'],
            'description' => 'Firm tofu marinated in spiced yoghurt-style dressing and roasted until the edges catch.',
            'ingredients' => [
                '400 g tofu',
                '200 g yoghurt',
                '2 tsp garam masala',
                '1 tsp turmeric',
                '1 tsp chilli powder',
                '1 tbsp ginger',
                '3 cloves garlic',
                '2 bell peppers',
                '1 onion',
                '2 tbsp vegetable oil',
                '1 lemon',
            ],
            'instructions' => [
                'Whisk the yoghurt with the spices, ginger, garlic and lemon juice.',
                'Cube the tofu and peppers, coat them in the marinade and rest for 25 minutes.',
                'Heat the oven to 220C for 10 minutes.',
                'Spread everything on a tray and roast for 18 minutes, turning once.',
                'Finish under the grill for 2 minutes to catch the edges.',
            ],
        ],
        [
            'title' => 'Peruvian Lomo Saltado',
            'cook' => 'ana',
            'country' => 'PE',
            'difficulty' => 'intermediate',
            'prep' => 20, 'cook_min' => 20, 'servings' => 3,
            'categories' => ['Dinner'],
            'diets' => ['dairy-free', 'high-protein'],
            'description' => 'Peru by way of a Chinese wok: beef, onions and tomatoes stir-fried with soy, served with chips and rice.',
            'ingredients' => [
                '500 g beef mince',
                '2 onions',
                '3 tomatoes',
                '400 g potatoes',
                '3 tbsp soy sauce',
                '2 tbsp vinegar',
                '3 cloves garlic',
                '250 g rice',
                '3 tbsp vegetable oil',
                '2 tbsp coriander',
            ],
            'instructions' => [
                'Cook the rice for 12 minutes and keep it covered.',
                'Fry the potato chips in oil for 8 minutes until golden, then drain them.',
                'Get a wok very hot and sear the beef for 3 minutes.',
                'Add the onions and garlic and stir-fry for 3 minutes.',
                'Add the tomatoes, soy sauce and vinegar and toss for 2 minutes.',
                'Fold the chips through, scatter with coriander and serve with rice.',
            ],
        ],
        [
            'title' => 'Chocolate Olive Oil Cake',
            'cook' => 'maria',
            'country' => 'ES',
            'difficulty' => 'beginner',
            'prep' => 15, 'cook_min' => 40, 'servings' => 8,
            'categories' => ['Dessert'],
            'diets' => ['vegetarian', 'dairy-free'],
            'description' => 'Dark, damp and dairy-free — olive oil does the work butter usually does.',
            'ingredients' => [
                '200 g flour',
                '200 g sugar',
                '150 ml olive oil',
                '100 g chocolate',
                '3 eggs',
                '1 tsp baking powder',
                '1 tsp vanilla',
                '1 pinch salt',
            ],
            'instructions' => [
                'Heat the oven to 170C and line a tin.',
                'Melt the chocolate with the olive oil and leave to cool for 5 minutes.',
                'Whisk the eggs with the sugar and vanilla for 4 minutes until pale and thick.',
                'Fold in the chocolate mixture, then the flour, baking powder and salt.',
                'Bake for 35 minutes until a skewer comes out with a few damp crumbs.',
                'Cool in the tin for 20 minutes before turning out.',
            ],
        ],
    ];

    /**
     * Second batch — widens the map into Africa, Oceania, North America and
     * the rest of Europe, and adds more overlap with common fridge staples so
     * the pantry search has plenty to rank.
     */
    private const MORE_RECIPES = [
        // ── Bangladesh ───────────────────────────────────────────────
        // The home cuisine, and the reason the local-cuisine bias exists.
        // Everything here is a dish somebody in Dhaka actually cooks on a
        // weeknight, built from ingredients already in the vocabulary.
        [
            'title' => 'Bhuna Khichuri',
            'cook' => 'rahim',
            'country' => 'BD',
            'difficulty' => 'beginner',
            'prep' => 10, 'cook_min' => 35, 'servings' => 4,
            'categories' => ['Dinner', 'Bengali', 'Quick Meals'],
            'diets' => ['vegetarian', 'halal', 'gluten-free', 'dairy-free'],
            'description' => 'Rice and lentils fried with whole spices before the water goes in, so it comes out separate and nutty rather than soupy. The thing you cook when it rains.',
            'ingredients' => [
                '2 cups rice',
                '1 cup lentils',
                '2 onions, sliced',
                '1 tbsp ginger',
                '4 cloves garlic',
                '1 tsp turmeric',
                '1 tsp cumin',
                '2 bay leaves',
                '4 cardamom pods',
                '1 stick cinnamon',
                '4 tbsp vegetable oil',
                '1.5 tsp salt',
            ],
            'instructions' => [
                'Rinse the rice and lentils together until the water runs clear, then drain well.',
                'Heat the oil and fry the bay leaves, cardamom and cinnamon for 1 minute until fragrant.',
                'Add the onions and cook for 8 minutes until golden, then stir in the ginger and garlic.',
                'Add the turmeric, cumin and salt, then the drained rice and lentils, and fry for 4 minutes.',
                'Pour in 5 cups of hot water, bring to the boil, then cover and cook on low for 20 minutes.',
                'Rest off the heat for 5 minutes before lifting the lid, then fold through gently.',
            ],
        ],
        [
            'title' => 'Aloo Bhorta',
            'cook' => 'rahim',
            'country' => 'BD',
            'difficulty' => 'beginner',
            'prep' => 5, 'cook_min' => 20, 'servings' => 4,
            'categories' => ['Lunch', 'Bengali', 'Vegan', 'Quick Meals'],
            'diets' => ['vegetarian', 'vegan', 'halal', 'gluten-free', 'dairy-free'],
            'description' => 'Mashed potato with raw mustard oil, green chilli and onion. Four ingredients, and the one dish every Bangladeshi kitchen can produce from an empty fridge.',
            'ingredients' => [
                '500 g potato',
                '1 onion, finely chopped',
                '3 green chillies, chopped',
                '2 tbsp mustard oil',
                '1 tsp salt',
                '2 tbsp coriander, chopped',
            ],
            'instructions' => [
                'Boil the potatoes whole for 20 minutes until a knife slides through, then peel while warm.',
                'Mash the potato roughly — it should keep some texture, not become a puree.',
                'Add the onion, green chilli and salt and work them through with your fingers.',
                'Pour over the raw mustard oil and mix until it smells sharp, then fold in the coriander.',
            ],
        ],
        [
            'title' => 'Begun Bhaja',
            'cook' => 'rahim',
            'country' => 'BD',
            'difficulty' => 'beginner',
            'prep' => 5, 'cook_min' => 12, 'servings' => 2,
            'categories' => ['Lunch', 'Bengali', 'Vegan', 'Quick Meals'],
            'diets' => ['vegetarian', 'vegan', 'halal', 'gluten-free', 'dairy-free'],
            'description' => 'Thick rounds of aubergine turmeric-rubbed and shallow fried until the edges go dark. Eaten with rice and dal, or straight off the plate before it reaches the table.',
            'ingredients' => [
                '1 aubergine, cut into thick rounds',
                '1 tsp turmeric',
                '1 tsp chilli powder',
                '1 tsp salt',
                '4 tbsp mustard oil',
            ],
            'instructions' => [
                'Rub the aubergine rounds on both sides with the turmeric, chilli powder and salt.',
                'Rest them for 10 minutes so the salt draws out some water.',
                'Heat the mustard oil until it just smokes, then lower the heat.',
                'Fry the rounds for 3 minutes a side until deep brown at the edges and soft through.',
                'Drain on paper and eat hot.',
            ],
        ],
        [
            'title' => 'Dim Bhuna',
            'cook' => 'rahim',
            'country' => 'BD',
            'difficulty' => 'beginner',
            'prep' => 10, 'cook_min' => 25, 'servings' => 4,
            'categories' => ['Dinner', 'Bengali'],
            'diets' => ['vegetarian', 'halal', 'gluten-free', 'dairy-free'],
            'description' => 'Boiled eggs fried until blistered, then folded into a thick onion masala. Fifteen minutes of actual work and it eats like something that took an hour.',
            'ingredients' => [
                '6 eggs',
                '3 onions, thinly sliced',
                '2 tomatoes, chopped',
                '4 cloves garlic',
                '1 tbsp ginger',
                '1 tsp turmeric',
                '1.5 tsp chilli powder',
                '1 tsp cumin',
                '4 tbsp vegetable oil',
                '1 tsp salt',
            ],
            'instructions' => [
                'Boil the eggs for 9 minutes, cool them under the tap and peel.',
                'Prick each egg a few times, rub with a little turmeric and salt, and fry in hot oil until blistered. Set aside.',
                'In the same oil cook the onions for 12 minutes until they collapse and turn brown.',
                'Add the garlic and ginger, then the turmeric, chilli powder and cumin with a splash of water.',
                'Stir in the tomatoes and cook for 6 minutes until the oil separates from the masala.',
                'Return the eggs, coat them, add a little water and simmer for 5 minutes.',
            ],
        ],
        [
            'title' => 'Murgir Jhol',
            'cook' => 'rahim',
            'country' => 'BD',
            'difficulty' => 'beginner',
            'prep' => 15, 'cook_min' => 35, 'servings' => 4,
            'categories' => ['Dinner', 'Bengali'],
            'diets' => ['halal', 'gluten-free', 'dairy-free'],
            'description' => 'The everyday chicken curry: thin golden broth, potatoes cooked in it until they start to fall apart, nothing fancy. What gets made when nobody has decided what to make.',
            'ingredients' => [
                '700 g chicken thigh',
                '3 potatoes, halved',
                '2 onions, sliced',
                '4 cloves garlic',
                '1 tbsp ginger',
                '1 tsp turmeric',
                '1 tsp chilli powder',
                '1 tsp cumin',
                '2 bay leaves',
                '3 tbsp vegetable oil',
                '1 tsp salt',
            ],
            'instructions' => [
                'Heat the oil and fry the bay leaves, then the onions for 8 minutes until soft and golden.',
                'Add the garlic and ginger and fry for 2 minutes.',
                'Add the turmeric, chilli powder, cumin and salt with a splash of water and cook the spices for 3 minutes.',
                'Add the chicken and turn it in the masala until coated and sealed, about 5 minutes.',
                'Add the potatoes and 3 cups of hot water, bring to the boil, then simmer uncovered for 25 minutes.',
                'The broth should be thin and the potatoes soft at the edges — do not reduce it to a paste.',
            ],
        ],
        [
            'title' => 'Shorshe Ilish',
            'cook' => 'rahim',
            'country' => 'BD',
            'difficulty' => 'intermediate',
            'prep' => 15, 'cook_min' => 20, 'servings' => 4,
            'categories' => ['Dinner', 'Bengali', 'Seafood'],
            'diets' => ['halal', 'gluten-free', 'dairy-free'],
            'description' => 'Hilsa steamed in mustard paste and green chilli. The national dish, and deliberately under-spiced — everything else here is there to stay out of the fish\'s way.',
            'ingredients' => [
                '6 pieces hilsa',
                '4 tbsp mustard paste',
                '6 green chillies, slit',
                '1 tsp turmeric',
                '5 tbsp mustard oil',
                '1 tsp salt',
            ],
            'instructions' => [
                'Rub the hilsa pieces with half the turmeric and salt and leave for 10 minutes.',
                'Loosen the mustard paste with half a cup of water, the rest of the turmeric and a pinch of salt.',
                'Lay the fish in a wide pan, pour the mustard mixture over and tuck in the green chillies.',
                'Pour the raw mustard oil over the top — it is not fried, it goes in cold.',
                'Cover and cook on a low heat for 12 minutes, turning the pieces once, very gently.',
                'Rest for 5 minutes before serving with plain rice. Do not stir it.',
            ],
        ],
        [
            'title' => 'Chingri Malai Curry',
            'cook' => 'rahim',
            'country' => 'BD',
            'difficulty' => 'intermediate',
            'prep' => 15, 'cook_min' => 25, 'servings' => 4,
            'categories' => ['Dinner', 'Bengali', 'Seafood'],
            'diets' => ['halal', 'gluten-free'],
            'description' => 'Prawns in coconut milk, barely spiced and slightly sweet. A wedding dish that is much easier than it looks, as long as you take the prawns out in time.',
            'ingredients' => [
                '500 g prawns',
                '400 ml coconut milk',
                '2 onions, blended to a paste',
                '1 tbsp ginger',
                '1 tsp turmeric',
                '1 tsp chilli powder',
                '1 tsp garam masala',
                '4 cardamom pods',
                '1 stick cinnamon',
                '4 tbsp vegetable oil',
                '1 tsp salt',
                '1 tsp sugar',
            ],
            'instructions' => [
                'Toss the prawns with the turmeric and salt, then fry them for 90 seconds a side and lift them out.',
                'In the same oil fry the cardamom and cinnamon, then the onion paste for 10 minutes until it loses its raw smell.',
                'Add the ginger, chilli powder and sugar and cook for 3 minutes.',
                'Pour in the coconut milk and bring it to a bare simmer — do not let it boil hard or it will split.',
                'Return the prawns for the last 4 minutes only, then finish with garam masala off the heat.',
            ],
        ],
        [
            'title' => 'Mishti Doi',
            'cook' => 'rahim',
            'country' => 'BD',
            'difficulty' => 'beginner',
            'prep' => 10, 'cook_min' => 30, 'servings' => 4,
            'categories' => ['Dessert', 'Bengali'],
            'diets' => ['vegetarian', 'halal', 'gluten-free'],
            'description' => 'Sweet set yoghurt, caramelised so it comes out the colour of wet sand. Made in a clay pot if you have one; a bowl and a warm cupboard also work.',
            'ingredients' => [
                '1 litre milk',
                '150 g sugar',
                '4 tbsp yoghurt',
            ],
            'instructions' => [
                'Melt a third of the sugar in a dry pan until it turns deep amber, watching it closely.',
                'Pour in the milk — it will hiss — add the rest of the sugar and reduce for 25 minutes until thickened.',
                'Cool the milk until it is just warm to a finger, no hotter, or the culture dies.',
                'Whisk in the yoghurt, pour into bowls and cover.',
                'Leave somewhere warm for 6 hours to set, then chill for at least 4 hours before eating.',
            ],
        ],

        [
            'title' => 'Jollof Rice',
            'cook' => 'amara',
            'country' => 'NG',
            'difficulty' => 'intermediate',
            'prep' => 20, 'cook_min' => 45, 'servings' => 6,
            'categories' => ['Dinner'],
            'diets' => ['vegetarian', 'gluten-free', 'dairy-free', 'halal'],
            'description' => 'Rice cooked in a deep, smoky pepper base until every grain is stained red. The party dish, and the argument starter.',
            'ingredients' => [
                '500 g rice',
                '400 g chopped tomatoes',
                '3 bell peppers',
                '2 onions',
                '4 cloves garlic',
                '1 tbsp ginger',
                '2 tsp paprika',
                '1 tsp curry powder',
                '1 tsp thyme',
                '2 bay leaves',
                '600 ml stock',
                '5 tbsp vegetable oil',
            ],
            'instructions' => [
                'Blend the peppers, one onion, the garlic and ginger into a smooth base.',
                'Fry the remaining sliced onion in oil for 6 minutes until soft.',
                'Pour in the blended base and cook it down for 15 minutes until it darkens and thickens.',
                'Stir in the tomatoes, paprika, curry powder, thyme and bay leaves and cook for 5 minutes.',
                'Add the rinsed rice and stock, cover tightly and steam for 25 minutes without stirring.',
                'Rest off the heat for 10 minutes, then fluff with a fork.',
            ],
        ],
        [
            'title' => 'Ethiopian Misir Wot',
            'cook' => 'amara',
            'country' => 'ET',
            'difficulty' => 'beginner',
            'prep' => 10, 'cook_min' => 40, 'servings' => 4,
            'categories' => ['Dinner', 'Vegan'],
            'diets' => ['vegetarian', 'vegan', 'gluten-free', 'dairy-free', 'halal'],
            'description' => 'Red lentils stewed low and slow with onion and berbere-style spice until they turn silky.',
            'ingredients' => [
                '300 g lentils',
                '3 onions',
                '4 cloves garlic',
                '1 tbsp ginger',
                '2 tbsp paprika',
                '2 tsp chilli powder',
                '1 tsp cumin',
                '1 tsp cardamom',
                '4 tbsp vegetable oil',
                '800 ml water',
            ],
            'instructions' => [
                'Cook the finely chopped onions dry in the pan for 8 minutes to drive off their water.',
                'Add the oil, garlic and ginger and fry for 3 minutes.',
                'Stir in the paprika, chilli, cumin and cardamom and cook the spices for 2 minutes.',
                'Add the rinsed lentils and water and simmer for 25 minutes, stirring now and then.',
                'Season and let it sit for 5 minutes so it thickens before serving.',
            ],
        ],
        [
            'title' => 'Moroccan Harira',
            'cook' => 'amara',
            'country' => 'MA',
            'difficulty' => 'intermediate',
            'prep' => 15, 'cook_min' => 50, 'servings' => 6,
            'categories' => ['Lunch'],
            'diets' => ['vegetarian', 'dairy-free', 'halal'],
            'description' => 'The soup that breaks the fast: lentils, chickpeas and tomato, thickened at the last minute and sharpened with lemon.',
            'ingredients' => [
                '200 g lentils',
                '400 g chickpeas',
                '400 g chopped tomatoes',
                '2 onions',
                '3 cloves garlic',
                '2 tsp cumin',
                '1 tsp turmeric',
                '1 tsp cinnamon',
                '3 tbsp coriander',
                '2 tbsp parsley',
                '1 lemon',
                '50 g flour',
                '1500 ml stock',
                '3 tbsp olive oil',
            ],
            'instructions' => [
                'Soften the onions and garlic in olive oil for 8 minutes.',
                'Add the cumin, turmeric and cinnamon and cook for 1 minute.',
                'Tip in the tomatoes, lentils, chickpeas and stock and simmer for 35 minutes.',
                'Whisk the flour into a cup of water and stir it in to thicken the soup.',
                'Simmer for 5 more minutes, then finish with the herbs and a squeeze of lemon.',
            ],
        ],
        [
            'title' => 'Shepherd\'s Pie',
            'cook' => 'tomas',
            'country' => 'GB',
            'difficulty' => 'intermediate',
            'prep' => 25, 'cook_min' => 45, 'servings' => 6,
            'categories' => ['Dinner'],
            'diets' => ['high-protein'],
            'description' => 'Braised mince under a mashed potato roof, baked until the peaks catch and crisp.',
            'ingredients' => [
                '700 g beef mince',
                '900 g potatoes',
                '2 onions',
                '3 carrots',
                '150 g peas',
                '3 cloves garlic',
                '2 tbsp tomato paste',
                '500 ml stock',
                '1 tsp thyme',
                '80 g butter',
                '100 ml milk',
                '2 tbsp vegetable oil',
            ],
            'instructions' => [
                'Boil the potatoes for 18 minutes until a knife slides through easily.',
                'Brown the mince hard in oil for 8 minutes, then set it aside.',
                'Fry the onions, carrots and garlic for 8 minutes until softening.',
                'Return the mince with the tomato paste, thyme and stock and simmer for 20 minutes.',
                'Mash the potatoes with the butter and milk until smooth.',
                'Stir the peas through the mince, top with mash, and bake for 25 minutes at 200C.',
            ],
        ],
        [
            'title' => 'French Onion Soup',
            'cook' => 'tomas',
            'country' => 'FR',
            'difficulty' => 'advanced',
            'prep' => 15, 'cook_min' => 75, 'servings' => 4,
            'categories' => ['Dinner'],
            'diets' => ['vegetarian'],
            'description' => 'An hour of patient stirring turns six onions into something that tastes like beef. Do not rush it.',
            'ingredients' => [
                '6 onions',
                '60 g butter',
                '2 tbsp olive oil',
                '3 cloves garlic',
                '1 tsp thyme',
                '2 bay leaves',
                '1200 ml stock',
                '4 slices bread',
                '150 g cheddar cheese',
            ],
            'instructions' => [
                'Melt the butter with the oil and add the thinly sliced onions with a big pinch of salt.',
                'Cook over low heat for 45 minutes, stirring every few minutes, until deep mahogany.',
                'Add the garlic, thyme and bay leaves and cook for 2 minutes.',
                'Pour in the stock and simmer gently for 20 minutes.',
                'Toast the bread for 4 minutes, pile on the cheese and grill until bubbling.',
                'Float a cheese toast on each bowl and serve immediately.',
            ],
        ],
        [
            'title' => 'Spanish Tortilla',
            'cook' => 'tomas',
            'country' => 'ES',
            'difficulty' => 'intermediate',
            'prep' => 10, 'cook_min' => 30, 'servings' => 4,
            'categories' => ['Breakfast', 'Lunch'],
            'diets' => ['vegetarian', 'gluten-free', 'dairy-free'],
            'description' => 'Potatoes poached soft in olive oil, then set in egg. Good hot, better at room temperature.',
            'ingredients' => [
                '600 g potatoes',
                '2 onions',
                '6 eggs',
                '200 ml olive oil',
                '1 tsp salt',
            ],
            'instructions' => [
                'Slice the potatoes thin and poach them gently in the olive oil for 18 minutes until tender but pale.',
                'Add the sliced onions for the last 6 minutes.',
                'Drain well, reserving the oil, and fold the potatoes into the beaten eggs.',
                'Rest the mixture for 10 minutes so the potato absorbs the egg.',
                'Cook in a hot oiled pan for 4 minutes, then flip onto a plate and slide back to cook the other side for 3 minutes.',
            ],
        ],
        [
            'title' => 'Polish Pierogi',
            'cook' => 'tomas',
            'country' => 'PL',
            'difficulty' => 'advanced',
            'prep' => 50, 'cook_min' => 20, 'servings' => 4,
            'categories' => ['Dinner'],
            'diets' => ['vegetarian'],
            'description' => 'Potato and cheese dumplings, boiled then fried in butter with onions until the edges blister.',
            'ingredients' => [
                '400 g flour',
                '1 egg',
                '200 ml water',
                '600 g potatoes',
                '200 g cheddar cheese',
                '2 onions',
                '80 g butter',
                '1 tsp salt',
            ],
            'instructions' => [
                'Work the flour, egg, water and salt into a soft dough and rest it for 30 minutes.',
                'Boil the potatoes for 18 minutes, then mash them with the grated cheese.',
                'Roll the dough thin, cut discs, fill and pinch them firmly shut.',
                'Boil the pierogi in batches for 4 minutes until they float.',
                'Fry the sliced onions in butter for 8 minutes, then add the pierogi and fry for 4 minutes until golden.',
            ],
        ],
        [
            'title' => 'Buttermilk Pancake Stack',
            'cook' => 'ana',
            'country' => 'US',
            'difficulty' => 'beginner',
            'prep' => 10, 'cook_min' => 15, 'servings' => 4,
            'categories' => ['Breakfast'],
            'diets' => ['vegetarian'],
            'description' => 'Thick, tender pancakes. The trick is to stop mixing while the batter still looks wrong.',
            'ingredients' => [
                '250 g flour',
                '2 tsp baking powder',
                '2 tbsp sugar',
                '2 eggs',
                '350 ml milk',
                '50 g butter',
                '1 tsp vanilla',
                '1 pinch salt',
            ],
            'instructions' => [
                'Whisk the flour, baking powder, sugar and salt together.',
                'Beat the eggs with the milk, melted butter and vanilla.',
                'Fold wet into dry until just combined — lumps are fine and desirable.',
                'Rest the batter for 10 minutes.',
                'Cook each pancake for 2 minutes until bubbles set, then 1 minute on the second side.',
            ],
        ],
        [
            'title' => 'Smash Burger with Crispy Onions',
            'cook' => 'ana',
            'country' => 'US',
            'difficulty' => 'beginner',
            'prep' => 10, 'cook_min' => 10, 'servings' => 2,
            'categories' => ['Lunch', 'Street Food'],
            'diets' => ['high-protein'],
            'description' => 'Thin patties pressed hard onto a screaming pan so the whole surface turns to crust.',
            'ingredients' => [
                '400 g beef mince',
                '1 onion',
                '4 slices cheddar cheese',
                '2 bread rolls',
                '2 tbsp butter',
                '1 tsp black pepper',
                '1 tsp salt',
            ],
            'instructions' => [
                'Divide the mince into four loose balls and refrigerate for 10 minutes.',
                'Get a heavy pan as hot as it will go.',
                'Press each ball flat for 90 seconds until a dark crust forms, then flip.',
                'Lay cheese on immediately and cook for 1 more minute.',
                'Fry the sliced onion in butter for 4 minutes and pile it on with the buns toasted.',
            ],
        ],
        [
            'title' => 'Poke Bowl',
            'cook' => 'yuki',
            'country' => 'US',
            'difficulty' => 'beginner',
            'prep' => 20, 'cook_min' => 12, 'servings' => 2,
            'categories' => ['Lunch', 'Seafood'],
            'diets' => ['pescatarian', 'dairy-free', 'high-protein'],
            'description' => 'Cold marinated fish over warm rice, with avocado and cucumber for contrast.',
            'ingredients' => [
                '300 g salmon',
                '250 g rice',
                '3 tbsp soy sauce',
                '1 tbsp vinegar',
                '1 tbsp ginger',
                '1 avocado',
                '1 cucumber',
                '2 spring onions',
                '1 lime',
            ],
            'instructions' => [
                'Cook the rice for 12 minutes and let it cool slightly.',
                'Dice the salmon and toss it with the soy sauce, vinegar and grated ginger.',
                'Chill the fish for 15 minutes while you slice the vegetables.',
                'Build the bowls with rice, fish, avocado and cucumber.',
                'Finish with spring onion and a squeeze of lime.',
            ],
        ],
        [
            'title' => 'Lamington Traybake',
            'cook' => 'tomas',
            'country' => 'AU',
            'difficulty' => 'intermediate',
            'prep' => 30, 'cook_min' => 30, 'servings' => 9,
            'categories' => ['Dessert'],
            'diets' => ['vegetarian'],
            'description' => 'Sponge squares rolled in chocolate and coconut. Sticky work, worth it.',
            'ingredients' => [
                '200 g flour',
                '200 g sugar',
                '4 eggs',
                '120 g butter',
                '2 tsp baking powder',
                '100 ml milk',
                '150 g chocolate',
                '1 tsp vanilla',
            ],
            'instructions' => [
                'Cream the butter and sugar for 5 minutes until pale.',
                'Beat in the eggs one at a time, then fold in the flour, baking powder and milk.',
                'Bake in a lined tin for 28 minutes at 180C.',
                'Cool completely for 60 minutes, then cut into squares.',
                'Melt the chocolate with a splash of milk, dip each square, and roll in coconut.',
            ],
        ],
        [
            'title' => 'Kiwi Green Breakfast Hash',
            'cook' => 'tomas',
            'country' => 'NZ',
            'difficulty' => 'beginner',
            'prep' => 10, 'cook_min' => 18, 'servings' => 2,
            'categories' => ['Breakfast', 'Quick Meals'],
            'diets' => ['vegetarian', 'gluten-free'],
            'description' => 'Crisp potatoes, wilted greens and a soft egg — brunch without the queue.',
            'ingredients' => [
                '400 g potatoes',
                '150 g spinach',
                '2 eggs',
                '1 avocado',
                '1 onion',
                '2 cloves garlic',
                '2 tbsp olive oil',
                '1 lemon',
                '1 tsp black pepper',
            ],
            'instructions' => [
                'Parboil the diced potatoes for 8 minutes and drain them dry.',
                'Fry them in olive oil for 10 minutes until the edges are crisp.',
                'Add the onion and garlic and cook for 4 minutes.',
                'Wilt the spinach through for 1 minute.',
                'Fry the eggs for 3 minutes and serve on top with avocado and lemon.',
            ],
        ],
        [
            'title' => 'Sri Lankan Coconut Dhal',
            'cook' => 'rahim',
            'country' => 'LK',
            'difficulty' => 'beginner',
            'prep' => 10, 'cook_min' => 25, 'servings' => 4,
            'categories' => ['Dinner', 'Vegan', 'Quick Meals'],
            'diets' => ['vegetarian', 'vegan', 'gluten-free', 'dairy-free', 'halal'],
            'description' => 'Lentils finished with coconut milk and a curry-leaf tempering. Weeknight food that tastes like a weekend.',
            'ingredients' => [
                '250 g lentils',
                '400 ml coconut milk',
                '1 onion',
                '3 cloves garlic',
                '1 tsp turmeric',
                '1 tsp cumin',
                '2 green chillies',
                '1 tsp curry powder',
                '3 tbsp vegetable oil',
                '500 ml water',
                '1 lime',
            ],
            'instructions' => [
                'Simmer the lentils with turmeric and water for 18 minutes until soft.',
                'Stir in the coconut milk and cook gently for 5 minutes.',
                'Heat the oil and fry the cumin for 30 seconds until it pops.',
                'Add the onion, garlic and chillies and fry for 5 minutes until golden.',
                'Pour the tempering over the dhal and finish with lime.',
            ],
        ],
        [
            'title' => 'Turkish Menemen',
            'cook' => 'rahim',
            'country' => 'TR',
            'difficulty' => 'beginner',
            'prep' => 5, 'cook_min' => 15, 'servings' => 2,
            'categories' => ['Breakfast', 'Quick Meals'],
            'diets' => ['vegetarian', 'gluten-free'],
            'description' => 'Soft-scrambled eggs folded through peppers and tomato, cooked slower than you think.',
            'ingredients' => [
                '4 eggs',
                '3 tomatoes',
                '2 bell peppers',
                '1 onion',
                '2 tbsp olive oil',
                '1 tsp paprika',
                '2 tbsp parsley',
                '1 tsp salt',
            ],
            'instructions' => [
                'Soften the sliced peppers and onion in olive oil for 8 minutes.',
                'Add the grated tomatoes and paprika and cook for 5 minutes until jammy.',
                'Lower the heat and pour in the beaten eggs.',
                'Fold slowly for 3 minutes until barely set — they keep cooking off the heat.',
                'Scatter with parsley and serve straight from the pan.',
            ],
        ],
    ];

    public function run(): void
    {
        $cooks = collect(self::COOKS)->mapWithKeys(function (array $cook) {
            [$name, $username, $email] = $cook;

            $user = User::firstOrCreate(
                ['email' => $email],
                [
                    'name' => $name,
                    'username' => $username,
                    'password' => Hash::make('DemoPass123!'),
                    'email_verified_at' => now(),
                    'skill_level' => 'intermediate',
                    'household_size' => 2,
                ]
            );

            return [$username => $user];
        });

        foreach (array_merge(self::RECIPES, self::MORE_RECIPES) as $row) {
            $author = $cooks[$row['cook']];

            $recipe = Recipe::updateOrCreate(
                ['title' => $row['title']],
                [
                    'user_id' => $author->id,
                    'description' => $row['description'],
                    'ingredients' => $row['ingredients'],
                    'instructions' => $row['instructions'],
                    'cuisine_code' => $row['country'],
                    'difficulty' => $row['difficulty'],
                    'prep_minutes' => $row['prep'],
                    'cook_minutes' => $row['cook_min'],
                    'servings' => $row['servings'],
                    'diet_tags' => $row['diets'],
                ]
            );

            $categoryIds = collect($row['categories'])
                ->map(fn (string $name) => Category::firstOrCreate(['name' => $name])->id);
            $recipe->categories()->sync($categoryIds);

            // Fills the ingredient pivot, normalises the cuisine fields and
            // computes per-serving nutrition.
            $this->sync->sync($recipe);

            // Generated dish illustration, so every seeded recipe has a picture.
            DishArtwork::attach($recipe->load('categories'));
        }

        // Recipes written straight to the model skip the controller's upload
        // reward, which would leave every seeded cook on zero and the
        // leaderboard flat. Award the same 10 points per published recipe.
        foreach ($cooks as $cook) {
            $cook->update(['points' => $cook->recipes()->count() * 10]);
        }
    }
}
