/**
 * The FridgeMama mark and wordmark.
 *
 * A red rounded square holding a fridge, with a green leaf tucked into its
 * corner — the whole pitch in one shape: the thing you own, and something
 * living inside it that you would rather not waste.
 *
 * Drawn rather than imported as a file so it stays sharp at any size, inherits
 * the page's colours, and costs no network request at a venue that has none.
 * The Android launcher icons are the same geometry, generated by
 * scripts/ (see client/public/icons); if this changes, they change with it.
 */

export function LogoMark({ size = 34, className = "" }) {
  const radius = Math.round(size * 0.32);

  return (
    <span
      className={`relative grid shrink-0 place-items-center text-white ${className}`}
      style={{
        width: size,
        height: size,
        borderRadius: radius,
        background: "var(--accent)",
      }}
      aria-hidden="true"
    >
      {/* The fridge: a rounded body, a door split, one handle per door. */}
      <svg
        width={size * 0.58}
        height={size * 0.58}
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2.2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <rect x="5" y="2" width="14" height="20" rx="3" />
        <path d="M5 10h14" />
        <path d="M15 6v1.5" />
        <path d="M15 13.5V15" />
      </svg>

      {/* The leaf, over the bottom-right corner. */}
      <svg
        width={size * 0.38}
        height={size * 0.38}
        viewBox="0 0 24 24"
        fill="var(--leaf)"
        className="absolute"
        style={{ right: -size * 0.09, bottom: -size * 0.09, transform: "rotate(-18deg)" }}
      >
        <path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z" />
      </svg>
    </span>
  );
}

/**
 * Mark plus name. `Mama` carries the lime, because that half is the promise —
 * anyone can list what is in a fridge; the point is that something is looking
 * after you.
 */
export default function Logo({ size = 34, className = "", tagline = null, compact = false }) {
  return (
    <span className={`inline-flex items-center gap-2.5 ${className}`}>
      <LogoMark size={size} />
      <span className="min-w-0">
        <span
          className="block font-extrabold leading-none tracking-[-0.06em] text-[var(--text)]"
          style={{ fontFamily: "var(--font-display)", fontSize: size * 0.58 }}
        >
          Fridge<span style={{ color: "var(--accent)" }}>Mama</span>
        </span>
        {tagline && !compact && (
          <span className="mt-1.5 block text-xs leading-snug text-[var(--faint)]">{tagline}</span>
        )}
      </span>
    </span>
  );
}
